Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2020-11, with the labels that each got.

#134 Allow multiple clusters (dhcpd) on same shared network
  modules/5_install/templates/install_vars.yaml
  variables.tf
Labels: approved, backport, lgtm, size/XS

#133 Allow multiple clusters (dhcpd) on same shared network
  modules/5_install/templates/install_vars.yaml
  variables.tf
Labels: approved, lgtm, size/XS

#130 Fix interpolation-only warnings
  modules/4_nodes/outputs.tf
  modules/5_install/install.tf
  variables.tf
Labels: approved, lgtm, size/S

#136 Support minimalistic 3-node OCP config
  docs/quickstart.md
  modules/3_helpernode/templates/helpernode_vars.yaml
  variables.tf
Labels: approved, lgtm, size/S

#137 Support minimalistic 3-node OCP config
  docs/quickstart.md
  modules/5_install/templates/helpernode_vars.yaml
  variables.tf
Labels: approved, backport, lgtm, size/S

#138 Support minimalistic 3-node OCP config
  docs/quickstart.md
  modules/3_helpernode/templates/helpernode_vars.yaml
  variables.tf
Labels: approved, backport, lgtm, size/S

#139 Simplify documentation
  README.md
  docs/automation_host_prereqs.md
  docs/coreos-image-creation.md
  docs/ocp_prereqs_powervc.md
  docs/quickstart.md
  docs/rhcos-image-creation.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/XL

#140 Simplify documentation
  README.md
  docs/automation_host_prereqs.md
  docs/coreos-image-creation.md
  docs/ocp_prereqs_powervc.md
  docs/quickstart.md
  docs/rhcos-image-creation.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/XL

#141 Minor modifications to master docs
  README.md
  docs/automation_host_prereqs.md
Labels: approved, lgtm, size/S
