Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2020-09, with the labels that each got.

#100 version constraint on providers and terraform binary
  README.md
  ocp.tf
Labels: do-not-merge/invalid-commit-message, lgtm, size/S

#105 Create OWNERS
  OWNERS
Labels: lgtm, size/XS

#103 Avoid downloading bootp files
  modules/5_install/templates/helpernode_vars.yaml
Labels: approved, lgtm, size/XS

#106 Start using Terraform 0.13
  README.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/versions.tf
  modules/3_network/versions.tf
  modules/4_nodes/versions.tf
  modules/5_install/versions.tf
  ocp.tf
  versions.tf
Labels: approved, lgtm, size/L

#108 Add instructions on release branches
  docs/quickstart.md
Labels: approved, lgtm, size/XS

#109 Support for OCP 4.6 installation
  modules/4_nodes/nodes.tf
  variables.tf
Labels: approved, lgtm, size/M

#115 Update ports to use dynamic block
  modules/2_network/network.tf
  modules/3_helpernode/outputs.tf
Labels: approved, lgtm, size/M

#117 Fix SRIOV binding failing when enabled
  modules/2_network/network.tf
Labels: approved, lgtm, size/S

#119 Add ignition fetch timeout
  modules/4_nodes/nodes.tf
Labels: approved, backport, lgtm, size/XS

#123 Add owners file
  OWNERS
Labels: size/XS

#124 Add ignition fetch timeout (#119)
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/S

#126 Change to new namespace for openstack provider
  modules/1_bastion/versions.tf
  modules/2_network/versions.tf
  modules/4_nodes/versions.tf
  versions.tf
Labels: approved, lgtm, size/S
