Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2021-04, with the labels that each got.

#194 [release-4.6] Network port creation only after bastion is ready
  modules/2_network/network.tf
  modules/2_network/variables.tf
  ocp.tf
Labels: approved, lgtm, size/XS

#193 [release-4.7] Network port creation only after bastion is ready
  modules/2_network/network.tf
  modules/2_network/variables.tf
  ocp.tf
Labels: approved, lgtm, size/XS

#195 [release-4.7] Update PowerVC prerequisites
  docs/ocp_prereqs_powervc.md
Labels: approved, lgtm, size/XS

#196 [release-4.6] Update PowerVC prerequisites
  docs/ocp_prereqs_powervc.md
Labels: approved, lgtm, size/XS

#197 Suport bastion HA
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/outputs.tf
  modules/1_bastion/variables.tf
  modules/2_network/network.tf
  modules/2_network/outputs.tf
  modules/2_network/variables.tf
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/templates/helpernode_inventory
  modules/3_helpernode/templates/helpernode_vars.yaml
  modules/3_helpernode/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/install_inventory
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  outputs.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#198 Backport PRs to release-4.6
  README.md
  docs/automation_host_prereqs.md
  docs/quickstart.md
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  modules/4_nodes/nodes.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/M

#204 Timeout added while removing worker node
  modules/4_nodes/nodes.tf
Labels: approved, lgtm, size/XS
