Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2021-07, with the labels that each got.

#213 Delaying nfs volume attach
  modules/1_bastion/bastion.tf
Labels: approved, lgtm, size/XS

#209 Enable bastion HA support to use pre-defined IPs, fix #208
  docs/var.tfvars-doc.md
  modules/2_network/network.tf
  modules/2_network/variables.tf
  ocp.tf
  variables.tf
Labels: approved, lgtm, size/S

#215 Implementation for #200
  docs/var.tfvars-doc.md
  modules/2_network/network.tf
  modules/2_network/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#212 To attach additional data volumes to nodes
  docs/var.tfvars-doc.md
  modules/4_nodes/nodes.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M
