Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2021-01, with the labels that each got.

#143 Image Upgrade on PowerVM
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#146 Update image upgrade code
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S

#147 Update image upgrade code
  docs/quickstart.md
  modules/5_install/install.tf
  modules/5_install/templates/upgrade_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/S

#152 Update default install playbook tag
  variables.tf
Labels: approved, lgtm, size/XS

#154 Update default install playbook tag
  variables.tf
Labels: approved, lgtm, size/XS

#151 Use pre-defined IP address for bastion node
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#153 Update default install playbook tag
  variables.tf
Labels: approved, lgtm, size/XS

#155 Use pre-defined IP address for bastion node
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm

#156 Use pre-defined IP address for bastion node
  docs/quickstart.md
  modules/1_bastion/bastion.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/XS

#157 Add activationkey support for RHEL subscription
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#158 Change module deependencies to include data sources
  modules/1_bastion/outputs.tf
  ocp.tf
Labels: approved, lgtm, size/XS
