Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2021-03, with the labels that each got.

#178 Add availability-zone as optinal attribute for OCP cluster nodes, Fix #179
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  modules/4_nodes/nodes.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#181 Use variable pull_secret_file for local registry
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/variables.tf
  ocp.tf
Labels: approved, lgtm, size/XS

#185 Use variable pull_secret_file for local registry
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/variables.tf
  ocp.tf
Labels: approved, backport, lgtm, size/XS

#187 Support specify cluster_id without prefix, Fix #88
  docs/var.tfvars-doc.md
  ocp.tf
  var.tfvars
Labels: approved, lgtm, size/XS

#188 Network port creation only after bastion is ready
  modules/2_network/network.tf
  modules/2_network/variables.tf
  ocp.tf
Labels: approved, lgtm, size/XS

#186 Use variable pull_secret_file for local registry
  modules/5_install/install.tf
Labels: approved, backport, lgtm, size/XS

#184 Use variable pull_secret_file for local registry
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/variables.tf
  ocp.tf
Labels: approved, backport, lgtm, size/XS

#190 Update PowerVC prerequisites
  docs/ocp_prereqs_powervc.md
Labels: approved, lgtm, size/XS
