Repository ocp-power-automation/ocp4-upi-powervm, pull requests merged in 2021-02, with the labels that each got.

#159 Use repo for ansible installation, Fixes: #98
  modules/1_bastion/bastion.tf
  modules/1_bastion/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#162 Added a new reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#161 Use hostnames instead of IP in inventory
  modules/3_helpernode/templates/helpernode_vars.yaml
  modules/5_install/install.tf
  modules/5_install/templates/inventory
Labels: approved, lgtm, size/S

#165 Add variable to set default CNI network provider
  docs/var.tfvars-doc.md
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/S

#167 Handle bootstrap count as 0
  modules/2_network/network.tf
  modules/2_network/outputs.tf
  modules/2_network/variables.tf
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/templates/helpernode_vars.yaml
  modules/5_install/install.tf
  modules/5_install/templates/inventory
  ocp.tf
  variables.tf
Labels: approved, lgtm, size/S

#160 Change module dependencies to include data sources
  modules/1_bastion/outputs.tf
  ocp.tf
Labels: approved, backport, lgtm, size/XS

#168 Allow adding and deleting worker nodes
  modules/3_helpernode/helpernode.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  ocp.tf
Labels: approved, lgtm, size/M

#169 Support running on Windows
  .gitattributes
  README.md
  docs/automation_host_prereqs.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/templates/create_disk_link.sh
Labels: approved, lgtm, size/XS

#171 Backport PRs to Release 4.6
  OWNERS
  docs/var.tfvars-doc.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/variables.tf
  modules/2_network/network.tf
  modules/2_network/outputs.tf
  modules/2_network/variables.tf
  modules/3_helpernode/helpernode.tf
  modules/3_helpernode/templates/helpernode_vars.yaml
  modules/4_nodes/nodes.tf
  modules/4_nodes/outputs.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/install_vars.yaml
  modules/5_install/templates/inventory
  modules/5_install/variables.tf
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, backport, lgtm, size/L

#173 Backport PRs to Release 4.5
  OWNERS
  modules/1_bastion/bastion.tf
  modules/1_bastion/variables.tf
  modules/3_network/network.tf
  modules/3_network/outputs.tf
  modules/3_network/variables.tf
  modules/4_nodes/nodes.tf
  modules/4_nodes/outputs.tf
  modules/4_nodes/variables.tf
  modules/5_install/install.tf
  modules/5_install/templates/helpernode_vars.yaml
  modules/5_install/templates/inventory
  ocp.tf
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/L

#172 Backport PRs to Release 4.6 (docs update and windows support)
  .gitattributes
  CONTRIBUTING.md
  README.md
  docs/automation_host_prereqs.md
  modules/1_bastion/bastion.tf
  modules/1_bastion/templates/create_disk_link.sh
Labels: approved, backport, lgtm

#175 Fix Ansible install on CentOS
  modules/1_bastion/bastion.tf
Labels: approved, lgtm, size/XS

#176 Fix Ansible install on CentOS (#175)
  modules/1_bastion/bastion.tf
Labels: approved, backport, lgtm, size/XS

#177 Replace references to OCP 4.7
  README.md
  docs/quickstart.md
  docs/rhcos-image-creation.md
  docs/var.tfvars-doc.md
  var.tfvars
  variables.tf
Labels: approved, lgtm, size/M

#166 Enable Terraform automation on Power, Fix: 33
  README.md
  docs/automation_host_prereqs.md
  docs/quickstart.md
Labels: approved, lgtm, size/S
